export const PROVIDERS = [
  { key: 'claude', label: 'Anthropic / Claude' },
  { key: 'openai', label: 'OpenAI' },
  { key: 'gemini', label: 'Google Gemini' },
];

export const ZONE_CONFIG = {
  offpeak: {
    key: 'offpeak',
    label: 'OFF-PEAK',
    color: '#22c55e',
    bgGlow: 'rgba(34, 197, 94, 0.12)',
    border: 'rgba(34, 197, 94, 0.35)',
    demand: 'LOW DEMAND',
    text: 'Best time to run heavy workloads.',
    subtext: 'Low latency and the widest scheduling headroom.',
    rec: 'Great time to work',
    recSub: 'Best window for long runs and large contexts',
    score: 20,
    badgeBg: 'rgba(34, 197, 94, 0.15)',
  },
  moderate: {
    key: 'moderate',
    label: 'MODERATE',
    color: '#f59e0b',
    bgGlow: 'rgba(245, 158, 11, 0.12)',
    border: 'rgba(245, 158, 11, 0.35)',
    demand: 'MODERATE DEMAND',
    text: 'Interactive traffic is building.',
    subtext: 'Good for normal prompts, but watch long jobs.',
    rec: 'Proceed carefully',
    recSub: 'Keep prompts tighter and monitor latency',
    score: 55,
    badgeBg: 'rgba(245, 158, 11, 0.15)',
  },
  peak: {
    key: 'peak',
    label: 'PEAK',
    color: '#ef4444',
    bgGlow: 'rgba(239, 68, 68, 0.12)',
    border: 'rgba(239, 68, 68, 0.35)',
    demand: 'HIGH DEMAND',
    text: 'Best to defer expensive or long-running work.',
    subtext: 'Expect higher contention and slower responses.',
    rec: 'Defer heavy tasks',
    recSub: 'Save big contexts and tool-heavy jobs for later',
    score: 90,
    badgeBg: 'rgba(239, 68, 68, 0.15)',
  },
};

export const DEFAULT_TRAFFIC_PROFILE = 'legacy-default';

export const TRAFFIC_PROFILES = {
  'ultra-frontier': {
    key: 'ultra-frontier',
    label: 'Premium frontier / pro',
    summary: 'For the heaviest premium frontier models used on long-running, high-value tasks.',
    inferenceNote: 'Inferred from official docs positioning these as the highest-compute options with slower, deeper reasoning and stronger agentic behavior.',
    scheduleLabel: 'Weekdays 10a-6p ET peak; 7a-10a and 6p-9p ET moderate',
    weekday: [
      { start: 0, end: 7, zone: 'offpeak' },
      { start: 7, end: 10, zone: 'moderate' },
      { start: 10, end: 18, zone: 'peak' },
      { start: 18, end: 21, zone: 'moderate' },
      { start: 21, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'frontier-reasoning': {
    key: 'frontier-reasoning',
    label: 'Frontier reasoning',
    summary: 'Conservative schedule for highest-capability reasoning models.',
    inferenceNote: 'Inferred from official model positioning and rate-limit posture. Providers do not publish fixed ET peak-hour schedules.',
    scheduleLabel: 'Weekdays 9a-5p ET peak; 7a-9a and 5p-8p ET moderate',
    weekday: [
      { start: 0, end: 7, zone: 'offpeak' },
      { start: 7, end: 9, zone: 'moderate' },
      { start: 9, end: 17, zone: 'peak' },
      { start: 17, end: 20, zone: 'moderate' },
      { start: 20, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'balanced-interactive': {
    key: 'balanced-interactive',
    label: 'Balanced interactive',
    summary: 'For general-purpose flagship and balanced models.',
    inferenceNote: 'Inferred from official docs plus model positioning around interactive latency and throughput.',
    scheduleLabel: 'Weekdays 8a-3p ET peak; 6a-8a and 3p-7p ET moderate',
    weekday: [
      { start: 0, end: 6, zone: 'offpeak' },
      { start: 6, end: 8, zone: 'moderate' },
      { start: 8, end: 15, zone: 'peak' },
      { start: 15, end: 19, zone: 'moderate' },
      { start: 19, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'high-throughput': {
    key: 'high-throughput',
    label: 'High-throughput / low-latency',
    summary: 'For mini, nano, flash, and lite models built for volume.',
    inferenceNote: 'Inferred from official docs emphasizing low latency, low cost, and high-volume operation.',
    scheduleLabel: 'Weekdays 11a-3p ET peak; 8a-11a and 3p-6p ET moderate',
    weekday: [
      { start: 0, end: 8, zone: 'offpeak' },
      { start: 8, end: 11, zone: 'moderate' },
      { start: 11, end: 15, zone: 'peak' },
      { start: 15, end: 18, zone: 'moderate' },
      { start: 18, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'realtime-audio': {
    key: 'realtime-audio',
    label: 'Realtime / speech preview',
    summary: 'For live dialogue and speech models where low-latency capacity matters more than batch throughput.',
    inferenceNote: 'Inferred from official docs positioning these models for real-time voice and low-latency audio. Providers do not publish fixed ET peak-hour schedules.',
    scheduleLabel: 'Weekdays 9a-4p ET peak; 7a-9a and 4p-8p ET moderate',
    weekday: [
      { start: 0, end: 7, zone: 'offpeak' },
      { start: 7, end: 9, zone: 'moderate' },
      { start: 9, end: 16, zone: 'peak' },
      { start: 16, end: 20, zone: 'moderate' },
      { start: 20, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'preview-balanced': {
    key: 'preview-balanced',
    label: 'Preview / variable capacity',
    summary: 'For preview models whose effective capacity is more volatile.',
    inferenceNote: 'Inferred from official docs that preview models often have tighter or changing limits.',
    scheduleLabel: 'Weekdays 10a-4p ET peak; 8a-10a and 4p-7p ET moderate',
    weekday: [
      { start: 0, end: 8, zone: 'offpeak' },
      { start: 8, end: 10, zone: 'moderate' },
      { start: 10, end: 16, zone: 'peak' },
      { start: 16, end: 19, zone: 'moderate' },
      { start: 19, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'legacy-default': {
    key: 'legacy-default',
    label: 'Legacy default fallback',
    summary: 'Fallback profile when there is no model-specific profile.',
    inferenceNote: 'This matches the app’s previous shared schedule and is used only as a fallback.',
    scheduleLabel: 'Weekdays 8a-2p ET peak; 6a-8a and 2p-6p ET moderate',
    weekday: [
      { start: 0, end: 6, zone: 'offpeak' },
      { start: 6, end: 8, zone: 'moderate' },
      { start: 8, end: 14, zone: 'peak' },
      { start: 14, end: 18, zone: 'moderate' },
      { start: 18, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
};

const MODEL_CATALOG = {
  claude: [
    {
      id: 'claude-opus-4-7',
      label: 'Claude Opus 4.7',
      status: 'latest',
      summary: 'Anthropic’s most capable generally available model for complex reasoning and agentic coding.',
      knowledgeCutoff: 'Jan 2026',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['claude-opus-4-7'],
      limits: { rpm: 'See Console', tpm: 'Shared Opus pool', ctx: '1M', out: '128K', batch: '300K with beta', tier: 'Anthropic usage tier' },
      source: {
        label: 'Anthropic models overview',
        url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
      },
      trafficProfile: 'ultra-frontier',
    },
    {
      id: 'claude-sonnet-4-6',
      label: 'Claude Sonnet 4.6',
      status: 'latest',
      summary: 'Anthropic’s best speed-intelligence balance for general coding, planning, and knowledge work.',
      knowledgeCutoff: 'Aug 2025',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['claude-sonnet-4-6'],
      limits: { rpm: 'See Console', tpm: 'Shared Sonnet 4.x pool', ctx: '1M', out: '64K', batch: '300K with beta', tier: 'Anthropic usage tier' },
      source: {
        label: 'Anthropic models overview',
        url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'claude-haiku-4-5',
      label: 'Claude Haiku 4.5',
      status: 'latest',
      summary: 'Anthropic’s fastest current model with near-frontier intelligence for lighter workloads.',
      knowledgeCutoff: 'Feb 2025',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['claude-haiku-4-5', 'claude-haiku-4-5-20251001', 'claude-haiku-4-5@20251001'],
      limits: { rpm: 'See Console', tpm: 'See Console', ctx: '200K', out: '64K', batch: 'See docs', tier: 'Anthropic usage tier' },
      source: {
        label: 'Anthropic models overview',
        url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
      },
      trafficProfile: 'high-throughput',
    },
  ],
  openai: [
    {
      id: 'gpt-5.5',
      label: 'GPT-5.5',
      status: 'latest',
      summary: 'OpenAI’s newest frontier model for complex reasoning, coding, and professional work.',
      knowledgeCutoff: 'Dec 01, 2025',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-5.5', 'gpt-5.5-2026-04-23'],
      limits: { rpm: '500', tpm: '500K', ctx: '1,050,000', out: '128K', batch: '1.5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI GPT-5.5 model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.5',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gpt-5.5-pro',
      label: 'GPT-5.5 pro',
      status: 'latest',
      summary: 'Higher-compute GPT-5.5 variant for precision-sensitive reasoning that may take minutes to complete.',
      knowledgeCutoff: 'Dec 01, 2025',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-5.5-pro', 'gpt-5.5-pro-2026-04-23'],
      limits: { rpm: '50', tpm: '50K', ctx: '1,050,000', out: '128K', batch: '500K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI GPT-5.5 pro model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.5-pro',
      },
      trafficProfile: 'ultra-frontier',
    },
    {
      id: 'gpt-5.4',
      label: 'GPT-5.4',
      status: 'current',
      summary: 'Affordable GPT-5-class model for coding and professional work when GPT-5.5 is unnecessary.',
      knowledgeCutoff: 'Dec 1, 2025',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-5.4'],
      limits: { rpm: '500', tpm: '500K', ctx: '1,050,000', out: '128K', batch: '1.5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI models overview',
        url: 'https://developers.openai.com/api/docs/models',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gpt-5.4-mini',
      label: 'GPT-5.4 mini',
      status: 'current',
      summary: 'Fast, efficient GPT-5-class model for high-volume coding and assistant workloads.',
      knowledgeCutoff: 'Aug 31, 2025',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-5.4-mini'],
      limits: { rpm: '500', tpm: '500K', ctx: '400K', out: '128K', batch: '5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI GPT-5.4 mini model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.4-mini',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gpt-5.4-nano',
      label: 'GPT-5.4 nano',
      status: 'current',
      summary: 'Lowest-cost GPT-5.4 variant for simple, throughput-heavy classification and extraction jobs.',
      knowledgeCutoff: 'See docs',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-5.4-nano'],
      limits: { rpm: '500', tpm: '200K', ctx: '400K', out: '128K', batch: '2M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI models overview',
        url: 'https://developers.openai.com/api/docs/models',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gpt-5-codex',
      label: 'GPT-5-Codex',
      status: 'current',
      summary: 'Current Codex-specialized GPT-5 variant optimized for long-horizon agentic coding workflows.',
      knowledgeCutoff: 'Sep 30, 2024',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-5-codex'],
      limits: { rpm: '500', tpm: '500K', ctx: '400K', out: '128K', batch: '1.5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI GPT-5-Codex model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5-codex',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gpt-realtime-2',
      label: 'GPT Realtime 2',
      status: 'latest',
      summary: 'OpenAI’s most capable realtime voice model for speech-to-speech agents and tool-rich voice workflows.',
      knowledgeCutoff: 'Sep 30, 2024',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-realtime-2'],
      limits: { rpm: 'See docs', tpm: 'See docs', ctx: '128K', out: '32K', batch: 'N/A', tier: 'Tiered' },
      source: {
        label: 'OpenAI gpt-realtime-2 model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-realtime-2',
      },
      trafficProfile: 'realtime-audio',
    },
    {
      id: 'gpt-realtime-1.5',
      label: 'GPT Realtime 1.5',
      status: 'current',
      summary: 'OpenAI’s flagship audio-in, audio-out voice model for production assistants and customer support.',
      knowledgeCutoff: 'Sep 30, 2024',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-realtime-1.5'],
      limits: { rpm: 'See docs', tpm: 'See docs', ctx: '32K', out: '4,096', batch: 'N/A', tier: 'Tiered' },
      source: {
        label: 'OpenAI gpt-realtime-1.5 model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-realtime-1.5',
      },
      trafficProfile: 'realtime-audio',
    },
    {
      id: 'gpt-realtime-mini',
      label: 'GPT Realtime mini',
      status: 'current',
      summary: 'Cost-efficient realtime model for lower-latency voice and audio applications.',
      knowledgeCutoff: 'Oct 01, 2023',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-realtime-mini', 'gpt-realtime-mini-2025-12-15'],
      limits: { rpm: 'See docs', tpm: 'See docs', ctx: '32K', out: '4,096', batch: 'N/A', tier: 'Tiered' },
      source: {
        label: 'OpenAI gpt-realtime-mini model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-realtime-mini',
      },
      trafficProfile: 'realtime-audio',
    },
    {
      id: 'gpt-realtime-translate',
      label: 'GPT Realtime Translate',
      status: 'latest',
      summary: 'Dedicated streaming speech-to-speech translation model for live multilingual audio experiences.',
      knowledgeCutoff: 'Sep 30, 2024',
      latestUpdate: 'Verified current May 24, 2026',
      versions: ['gpt-realtime-translate'],
      limits: { rpm: 'See docs', tpm: 'Audio-duration priced', ctx: '16K', out: '2,000', batch: 'N/A', tier: 'Tiered' },
      source: {
        label: 'OpenAI gpt-realtime-translate model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-realtime-translate',
      },
      trafficProfile: 'realtime-audio',
    },
  ],
  gemini: [
    {
      id: 'gemini-3.1-pro-preview',
      label: 'Gemini 3.1 Pro Preview',
      status: 'latest preview',
      summary: 'Google’s newest top-end Gemini preview for multimodal reasoning, agentic coding, and long-context work.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Released Feb 19, 2026',
      versions: ['Preview: gemini-3.1-pro-preview'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: 'Supported', tier: 'Preview / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gemini-3.5-flash',
      label: 'Gemini 3.5 Flash',
      status: 'latest stable',
      summary: 'Google’s newest stable Gemini workhorse for fast multimodal and agentic application traffic.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Released May 19, 2026',
      versions: ['Stable: gemini-3.5-flash'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: 'Supported', tier: 'Stable / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gemini-3-flash-preview',
      label: 'Gemini 3 Flash Preview',
      status: 'current preview',
      summary: 'Balanced Gemini 3 preview retained while Google steers most production traffic toward Gemini 3.5 Flash.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Released Dec 17, 2025',
      versions: ['Preview: gemini-3-flash-preview'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: 'Supported', tier: 'Preview / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'preview-balanced',
    },
    {
      id: 'gemini-3.1-flash-lite',
      label: 'Gemini 3.1 Flash-Lite',
      status: 'latest stable',
      summary: 'Google’s newest low-cost stable Gemini model for high-throughput assistant and extraction workloads.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Released May 7, 2026',
      versions: ['Stable: gemini-3.1-flash-lite'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: 'Supported', tier: 'Stable / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gemini-3.1-flash-image-preview',
      label: 'Gemini 3.1 Flash Image Preview',
      status: 'current preview',
      summary: 'Google’s newest Gemini image-generation and editing endpoint for conversational multimodal workflows.',
      knowledgeCutoff: 'See docs',
      latestUpdate: 'Released Feb 26, 2026',
      versions: ['Preview: gemini-3.1-flash-image-preview'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '32,768', out: '32,768', batch: 'N/A', tier: 'Preview / Image' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'preview-balanced',
    },
    {
      id: 'gemini-3.1-flash-live-preview',
      label: 'Gemini 3.1 Flash Live Preview',
      status: 'current preview',
      summary: 'Current low-latency Gemini live model for real-time dialogue, voice-first assistants, and bidirectional audio.',
      knowledgeCutoff: 'See docs',
      latestUpdate: 'Released Mar 11, 2026',
      versions: ['Preview: gemini-3.1-flash-live-preview'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: 'See docs', out: 'See docs', batch: 'N/A', tier: 'Preview / Live API' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'realtime-audio',
    },
    {
      id: 'gemini-3.1-flash-tts-preview',
      label: 'Gemini 3.1 Flash TTS Preview',
      status: 'current preview',
      summary: 'Current Gemini preview TTS model for low-latency speech generation with steerable voice output.',
      knowledgeCutoff: 'See docs',
      latestUpdate: 'Released Apr 13, 2026',
      versions: ['Preview: gemini-3.1-flash-tts-preview'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '8,192', out: '16,384', batch: 'Supported', tier: 'Preview / TTS' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'realtime-audio',
    },
    {
      id: 'gemini-2.5-pro',
      label: 'Gemini 2.5 Pro',
      status: 'transitioning',
      summary: 'Still-available Gemini reasoning model with an announced replacement path toward Gemini 3.1 Pro Preview.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Shutdown announced for Oct 16, 2026',
      versions: ['Stable: gemini-2.5-pro'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: 'Supported', tier: 'Stable / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gemini-2.5-flash',
      label: 'Gemini 2.5 Flash',
      status: 'transitioning',
      summary: 'Still-available Gemini flash model with Google’s recommended replacement now set to Gemini 3.5 Flash.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Shutdown announced for Oct 16, 2026',
      versions: ['Stable: gemini-2.5-flash'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: 'Supported', tier: 'Stable / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gemini-2.5-flash-lite',
      label: 'Gemini 2.5 Flash-Lite',
      status: 'transitioning',
      summary: 'Still-available low-cost Gemini tier that now sits behind Gemini 3.1 Flash-Lite.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Shutdown announced for Oct 16, 2026',
      versions: ['Stable: gemini-2.5-flash-lite'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: 'Supported', tier: 'Stable / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gemini-2.5-flash-image',
      label: 'Gemini 2.5 Flash Image',
      status: 'transitioning',
      summary: 'Still-available image model that Google now points users away from in favor of Gemini 3.1 Flash Image Preview.',
      knowledgeCutoff: 'June 2025',
      latestUpdate: 'Shutdown announced for Oct 2, 2026',
      versions: ['Stable: gemini-2.5-flash-image'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '32,768', out: '32,768', batch: 'N/A', tier: 'Stable / Image' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'preview-balanced',
    },
  ],
};

const allModels = Object.values(MODEL_CATALOG).flat();

export const MODEL_DETAILS = Object.fromEntries(
  allModels.map((model) => [model.id, model])
);

export const MODELS = Object.fromEntries(
  Object.entries(MODEL_CATALOG).map(([provider, models]) => [
    provider,
    models.map(({ id }) => id),
  ])
);

export const DEFAULT_MODEL_BY_PROVIDER = Object.fromEntries(
  Object.entries(MODEL_CATALOG).map(([provider, models]) => [provider, models[0]?.id])
);

export const MODEL_LIMITS = Object.fromEntries(
  allModels.map((model) => [
    model.id,
    {
      rpm: model.limits.rpm,
      tpm: model.limits.tpm,
      ctx: model.limits.ctx,
      out: model.limits.out,
      batch: model.limits.batch,
      tier: model.limits.tier,
    },
  ])
);

export function getModelDetails(modelId) {
  return MODEL_DETAILS[modelId];
}

export function getTrafficProfileForModel(modelId) {
  const profileKey = MODEL_DETAILS[modelId]?.trafficProfile || DEFAULT_TRAFFIC_PROFILE;
  return TRAFFIC_PROFILES[profileKey] || TRAFFIC_PROFILES[DEFAULT_TRAFFIC_PROFILE];
}
