export const PROVIDERS = [
  { key: 'claude', label: 'Anthropic / Claude' },
  { key: 'openai', label: 'OpenAI' },
  { key: 'gemini', label: 'Google Gemini' },
];

export const ZONE_CONFIG = {
  offpeak: {
    key: 'offpeak',
    label: 'OFF-PEAK',
    color: '#22c55e',
    bgGlow: 'rgba(34, 197, 94, 0.12)',
    border: 'rgba(34, 197, 94, 0.35)',
    demand: 'LOW DEMAND',
    text: 'Best time to run heavy workloads.',
    subtext: 'Low latency and the widest scheduling headroom.',
    rec: 'Great time to work',
    recSub: 'Best window for long runs and large contexts',
    score: 20,
    badgeBg: 'rgba(34, 197, 94, 0.15)',
  },
  moderate: {
    key: 'moderate',
    label: 'MODERATE',
    color: '#f59e0b',
    bgGlow: 'rgba(245, 158, 11, 0.12)',
    border: 'rgba(245, 158, 11, 0.35)',
    demand: 'MODERATE DEMAND',
    text: 'Interactive traffic is building.',
    subtext: 'Good for normal prompts, but watch long jobs.',
    rec: 'Proceed carefully',
    recSub: 'Keep prompts tighter and monitor latency',
    score: 55,
    badgeBg: 'rgba(245, 158, 11, 0.15)',
  },
  peak: {
    key: 'peak',
    label: 'PEAK',
    color: '#ef4444',
    bgGlow: 'rgba(239, 68, 68, 0.12)',
    border: 'rgba(239, 68, 68, 0.35)',
    demand: 'HIGH DEMAND',
    text: 'Best to defer expensive or long-running work.',
    subtext: 'Expect higher contention and slower responses.',
    rec: 'Defer heavy tasks',
    recSub: 'Save big contexts and tool-heavy jobs for later',
    score: 90,
    badgeBg: 'rgba(239, 68, 68, 0.15)',
  },
};

export const DEFAULT_TRAFFIC_PROFILE = 'legacy-default';

export const TRAFFIC_PROFILES = {
  'ultra-frontier': {
    key: 'ultra-frontier',
    label: 'Premium frontier / pro',
    summary: 'For the heaviest premium frontier models used on long-running, high-value tasks.',
    inferenceNote: 'Inferred from official docs positioning these as the highest-compute options with slower, deeper reasoning and stronger agentic behavior.',
    scheduleLabel: 'Weekdays 10a-6p ET peak; 7a-10a and 6p-9p ET moderate',
    weekday: [
      { start: 0, end: 7, zone: 'offpeak' },
      { start: 7, end: 10, zone: 'moderate' },
      { start: 10, end: 18, zone: 'peak' },
      { start: 18, end: 21, zone: 'moderate' },
      { start: 21, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'frontier-reasoning': {
    key: 'frontier-reasoning',
    label: 'Frontier reasoning',
    summary: 'Conservative schedule for highest-capability reasoning models.',
    inferenceNote: 'Inferred from official model positioning and rate-limit posture. Providers do not publish fixed ET peak-hour schedules.',
    scheduleLabel: 'Weekdays 9a-5p ET peak; 7a-9a and 5p-8p ET moderate',
    weekday: [
      { start: 0, end: 7, zone: 'offpeak' },
      { start: 7, end: 9, zone: 'moderate' },
      { start: 9, end: 17, zone: 'peak' },
      { start: 17, end: 20, zone: 'moderate' },
      { start: 20, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'balanced-interactive': {
    key: 'balanced-interactive',
    label: 'Balanced interactive',
    summary: 'For general-purpose flagship and balanced models.',
    inferenceNote: 'Inferred from official docs plus model positioning around interactive latency and throughput.',
    scheduleLabel: 'Weekdays 8a-3p ET peak; 6a-8a and 3p-7p ET moderate',
    weekday: [
      { start: 0, end: 6, zone: 'offpeak' },
      { start: 6, end: 8, zone: 'moderate' },
      { start: 8, end: 15, zone: 'peak' },
      { start: 15, end: 19, zone: 'moderate' },
      { start: 19, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'high-throughput': {
    key: 'high-throughput',
    label: 'High-throughput / low-latency',
    summary: 'For mini, nano, flash, and lite models built for volume.',
    inferenceNote: 'Inferred from official docs emphasizing low latency, low cost, and high-volume operation.',
    scheduleLabel: 'Weekdays 11a-3p ET peak; 8a-11a and 3p-6p ET moderate',
    weekday: [
      { start: 0, end: 8, zone: 'offpeak' },
      { start: 8, end: 11, zone: 'moderate' },
      { start: 11, end: 15, zone: 'peak' },
      { start: 15, end: 18, zone: 'moderate' },
      { start: 18, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'preview-balanced': {
    key: 'preview-balanced',
    label: 'Preview / variable capacity',
    summary: 'For preview models whose effective capacity is more volatile.',
    inferenceNote: 'Inferred from official docs that preview models often have tighter or changing limits.',
    scheduleLabel: 'Weekdays 10a-4p ET peak; 8a-10a and 4p-7p ET moderate',
    weekday: [
      { start: 0, end: 8, zone: 'offpeak' },
      { start: 8, end: 10, zone: 'moderate' },
      { start: 10, end: 16, zone: 'peak' },
      { start: 16, end: 19, zone: 'moderate' },
      { start: 19, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
  'legacy-default': {
    key: 'legacy-default',
    label: 'Legacy default fallback',
    summary: 'Fallback profile when there is no model-specific profile.',
    inferenceNote: 'This matches the app’s previous shared schedule and is used only as a fallback.',
    scheduleLabel: 'Weekdays 8a-2p ET peak; 6a-8a and 2p-6p ET moderate',
    weekday: [
      { start: 0, end: 6, zone: 'offpeak' },
      { start: 6, end: 8, zone: 'moderate' },
      { start: 8, end: 14, zone: 'peak' },
      { start: 14, end: 18, zone: 'moderate' },
      { start: 18, end: 24, zone: 'offpeak' },
    ],
    weekend: [{ start: 0, end: 24, zone: 'offpeak' }],
  },
};

const MODEL_CATALOG = {
  claude: [
    {
      id: 'claude-opus-4-7',
      label: 'Claude Opus 4.7',
      status: 'latest',
      summary: 'Anthropic’s most capable generally available model for complex reasoning and agentic coding.',
      knowledgeCutoff: 'Jan 2026',
      latestUpdate: 'Released Apr 16, 2026',
      versions: ['claude-opus-4-7'],
      limits: { rpm: 'See Console', tpm: 'Shared Opus pool', ctx: '1M', out: '128K', batch: '300K with beta', tier: 'Anthropic usage tier' },
      source: {
        label: 'Anthropic models overview',
        url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
      },
      trafficProfile: 'ultra-frontier',
    },
    {
      id: 'claude-opus-4-6',
      label: 'Claude Opus 4.6',
      status: 'current',
      summary: 'Previous Opus generation still active for deep reasoning, coding, and long-horizon agents.',
      knowledgeCutoff: 'May 2025',
      latestUpdate: 'Released Feb 5, 2026',
      versions: ['claude-opus-4-6'],
      limits: { rpm: 'See Console', tpm: 'Shared Opus pool', ctx: '200K / 1M beta', out: '128K', batch: '300K with beta', tier: 'Anthropic usage tier' },
      source: {
        label: 'Anthropic Opus 4.6 note',
        url: 'https://www.anthropic.com/news/claude-opus-4-6',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'claude-sonnet-4-6',
      label: 'Claude Sonnet 4.6',
      status: 'current',
      summary: 'Balanced Claude model with adaptive and extended thinking.',
      knowledgeCutoff: 'Aug 2025',
      latestUpdate: 'Released Feb 17, 2026',
      versions: ['claude-sonnet-4-6'],
      limits: { rpm: 'See Console', tpm: 'Shared Sonnet 4.x pool', ctx: '200K / 1M beta', out: '64K', batch: '300K with beta', tier: 'Anthropic usage tier' },
      source: {
        label: 'Anthropic models overview',
        url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'claude-haiku-4-5',
      label: 'Claude Haiku 4.5',
      status: 'current',
      summary: 'Fastest current Claude class for lightweight reasoning and chat.',
      knowledgeCutoff: 'Feb 2025',
      latestUpdate: 'Released Oct 1, 2025',
      versions: ['claude-haiku-4-5', 'claude-haiku-4-5-20251001'],
      limits: { rpm: 'See Console', tpm: 'See Console', ctx: '200K', out: '64K', batch: 'See docs', tier: 'Anthropic usage tier' },
      source: {
        label: 'Anthropic models overview',
        url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'claude-opus-4-5',
      label: 'Claude Opus 4.5',
      status: 'previous',
      summary: 'Earlier Opus snapshot retained for compatibility with older deployments.',
      knowledgeCutoff: 'See docs',
      latestUpdate: 'Snapshot Nov 1, 2025',
      versions: ['claude-opus-4-5-20251101'],
      limits: { rpm: 'See Console', tpm: 'Shared Opus pool', ctx: '200K+', out: 'See docs', batch: 'See docs', tier: 'Anthropic tiered' },
      source: {
        label: 'Anthropic model deprecations',
        url: 'https://platform.claude.com/docs/en/about-claude/model-deprecations',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'claude-sonnet-4-5',
      label: 'Claude Sonnet 4.5',
      status: 'previous',
      summary: 'Previous balanced Sonnet release.',
      knowledgeCutoff: 'Jan 2025',
      latestUpdate: 'Snapshot Sep 29, 2025',
      versions: ['claude-sonnet-4-5-20250929'],
      limits: { rpm: 'See Console', tpm: 'Shared Sonnet 4.x pool', ctx: '200K+', out: 'See docs', batch: 'See docs', tier: 'Anthropic tiered' },
      source: {
        label: 'Anthropic model deprecations',
        url: 'https://platform.claude.com/docs/en/about-claude/model-deprecations',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'claude-3-5-haiku-20241022',
      label: 'Claude Haiku 3.5',
      status: 'retired',
      summary: 'Retired older fast Claude option kept only for historical comparison.',
      knowledgeCutoff: 'See docs',
      latestUpdate: 'Retired Feb 19, 2026',
      versions: ['claude-3-5-haiku-20241022'],
      limits: { rpm: 'See Console', tpm: 'See Console', ctx: '200K', out: 'See docs', batch: 'See docs', tier: 'Anthropic tiered' },
      source: {
        label: 'Anthropic model deprecations',
        url: 'https://platform.claude.com/docs/en/about-claude/model-deprecations',
      },
      trafficProfile: 'high-throughput',
    },
  ],
  openai: [
    {
      id: 'gpt-5.4-pro',
      label: 'GPT-5.4 pro',
      status: 'latest',
      summary: 'Highest-end GPT-5.4 variant for the hardest coding, agentic, and research tasks.',
      knowledgeCutoff: 'Aug 31, 2025',
      latestUpdate: 'Snapshot 2026-03-05',
      versions: ['gpt-5.4-pro', 'gpt-5.4-pro-2026-03-05'],
      limits: { rpm: '500', tpm: '30K', ctx: '1,050,000', out: '128K', batch: '90K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.4-pro',
      },
      trafficProfile: 'ultra-frontier',
    },
    {
      id: 'gpt-5.4',
      label: 'GPT-5.4',
      status: 'current',
      summary: 'OpenAI flagship for agentic, coding, and professional workflows.',
      knowledgeCutoff: 'Aug 31, 2025',
      latestUpdate: 'Snapshot 2026-03-05',
      versions: ['gpt-5.4', 'gpt-5.4-2026-03-05'],
      limits: { rpm: '500', tpm: '500K', ctx: '1,050,000', out: '128K', batch: '1.5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.4',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gpt-5.4-mini',
      label: 'GPT-5.4 mini',
      status: 'current',
      summary: 'High-volume GPT-5.4 variant for coding and subagents.',
      knowledgeCutoff: 'Aug 31, 2025',
      latestUpdate: 'Snapshot 2026-03-17',
      versions: ['gpt-5.4-mini', 'gpt-5.4-mini-2026-03-17'],
      limits: { rpm: '500', tpm: '500K', ctx: '400K', out: '128K', batch: '5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.4-mini',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gpt-5.4-nano',
      label: 'GPT-5.4 nano',
      status: 'current',
      summary: 'Cheapest GPT-5.4-class model for simple high-volume tasks.',
      knowledgeCutoff: 'Aug 31, 2025',
      latestUpdate: 'Snapshot 2026-03-17',
      versions: ['gpt-5.4-nano', 'gpt-5.4-nano-2026-03-17'],
      limits: { rpm: '500', tpm: '200K', ctx: '400K', out: '128K', batch: '2M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.4-nano',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gpt-5.2-pro',
      label: 'GPT-5.2 pro',
      status: 'previous',
      summary: 'Previous pro frontier model for complex professional work that still remains available.',
      knowledgeCutoff: 'Aug 31, 2025',
      latestUpdate: 'Snapshot 2025-12-11',
      versions: ['gpt-5.2-pro', 'gpt-5.2-pro-2025-12-11'],
      limits: { rpm: '500', tpm: '30K', ctx: '400K', out: '128K', batch: '90K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.2-pro',
      },
      trafficProfile: 'ultra-frontier',
    },
    {
      id: 'gpt-5.2',
      label: 'GPT-5.2',
      status: 'previous',
      summary: 'Previous frontier model for professional work with configurable reasoning effort.',
      knowledgeCutoff: 'Aug 31, 2025',
      latestUpdate: 'Snapshot 2025-12-11',
      versions: ['gpt-5.2', 'gpt-5.2-2025-12-11'],
      limits: { rpm: '500', tpm: '500K', ctx: '400K', out: '128K', batch: '1.5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.2',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gpt-5-pro',
      label: 'GPT-5 pro',
      status: 'previous',
      summary: 'Earlier GPT-5 pro release that uses more compute for harder reasoning tasks.',
      knowledgeCutoff: 'Sep 30, 2024',
      latestUpdate: 'Snapshot 2025-10-06',
      versions: ['gpt-5-pro', 'gpt-5-pro-2025-10-06'],
      limits: { rpm: '500', tpm: '30K', ctx: '400K', out: '272K', batch: '90K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5-pro',
      },
      trafficProfile: 'ultra-frontier',
    },
    {
      id: 'gpt-5.1',
      label: 'GPT-5.1',
      status: 'current',
      summary: 'Late-2025 GPT-5 generation kept for teams pinned to the 5.1 release.',
      knowledgeCutoff: 'Sep 30, 2024',
      latestUpdate: 'Snapshot 2025-11-13',
      versions: ['gpt-5.1', 'gpt-5.1-2025-11-13'],
      limits: { rpm: '500', tpm: '500K', ctx: '400K', out: '128K', batch: '1.5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5.1',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gpt-5',
      label: 'GPT-5',
      status: 'previous',
      summary: 'Previous intelligent reasoning model; docs recommend newer GPT-5.x models.',
      knowledgeCutoff: 'Sep 30, 2024',
      latestUpdate: 'Snapshot 2025-08-07',
      versions: ['gpt-5', 'gpt-5-2025-08-07'],
      limits: { rpm: '500', tpm: '500K', ctx: '400K', out: '128K', batch: '1.5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gpt-5-mini',
      label: 'GPT-5 mini',
      status: 'previous',
      summary: 'Earlier GPT-5 mini release; OpenAI now recommends GPT-5.4 mini for new low-latency workloads.',
      knowledgeCutoff: 'May 31, 2024',
      latestUpdate: 'Snapshot 2025-08-07',
      versions: ['gpt-5-mini', 'gpt-5-mini-2025-08-07'],
      limits: { rpm: '500', tpm: '500K', ctx: '400K', out: '128K', batch: '5M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5-mini',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gpt-5-nano',
      label: 'GPT-5 nano',
      status: 'previous',
      summary: 'Earlier GPT-5 nano release; OpenAI now recommends GPT-5.4 nano for new speed-first workloads.',
      knowledgeCutoff: 'May 31, 2024',
      latestUpdate: 'Snapshot 2025-08-07',
      versions: ['gpt-5-nano', 'gpt-5-nano-2025-08-07'],
      limits: { rpm: '500', tpm: '200K', ctx: '400K', out: '128K', batch: '2M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-5-nano',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gpt-4.5-preview',
      label: 'GPT-4.5 Preview',
      status: 'deprecated',
      summary: 'Deprecated research preview retained because many teams still look for it explicitly.',
      knowledgeCutoff: 'Oct 01, 2023',
      latestUpdate: 'Snapshot 2025-02-27',
      versions: ['gpt-4.5-preview', 'gpt-4.5-preview-2025-02-27'],
      limits: { rpm: '1,000', tpm: '125K', ctx: '128K', out: '16,384', batch: '50K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-4.5-preview',
      },
      trafficProfile: 'preview-balanced',
    },
    {
      id: 'gpt-4.1',
      label: 'GPT-4.1',
      status: 'current',
      summary: 'Current non-reasoning flagship in the GPT-4.1 family.',
      knowledgeCutoff: 'Jun 01, 2024',
      latestUpdate: 'Snapshot 2025-04-14',
      versions: ['gpt-4.1', 'gpt-4.1-2025-04-14'],
      limits: { rpm: '500', tpm: '30K', ctx: '1,047,576', out: '32,768', batch: '90K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-4.1',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gpt-4.1-mini',
      label: 'GPT-4.1 mini',
      status: 'current',
      summary: 'Smaller GPT-4.1 variant optimized for latency and cost.',
      knowledgeCutoff: 'Jun 01, 2024',
      latestUpdate: 'Snapshot 2025-04-14',
      versions: ['gpt-4.1-mini', 'gpt-4.1-mini-2025-04-14'],
      limits: { rpm: '500', tpm: '200K', ctx: '1,047,576', out: '32,768', batch: '2M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-4.1-mini',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gpt-4.1-nano',
      label: 'GPT-4.1 nano',
      status: 'current',
      summary: 'Cheapest GPT-4.1 variant for low-latency routing, extraction, and classification.',
      knowledgeCutoff: 'Jun 01, 2024',
      latestUpdate: 'Snapshot 2025-04-14',
      versions: ['gpt-4.1-nano', 'gpt-4.1-nano-2025-04-14'],
      limits: { rpm: '500', tpm: '200K', ctx: '1,047,576', out: '32,768', batch: '2M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/gpt-4.1-nano',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'o3-pro',
      label: 'o3-pro',
      status: 'current',
      summary: 'OpenAI pro reasoning model for slower, harder multi-step technical work.',
      knowledgeCutoff: 'Jun 01, 2024',
      latestUpdate: 'Snapshot 2025-06-10',
      versions: ['o3-pro', 'o3-pro-2025-06-10'],
      limits: { rpm: '500', tpm: '30K', ctx: '200K', out: '100K', batch: '90K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/o3-pro',
      },
      trafficProfile: 'ultra-frontier',
    },
    {
      id: 'o3',
      label: 'o3',
      status: 'previous',
      summary: 'Earlier reasoning model retained for comparison; OpenAI says GPT-5 succeeds it for many uses.',
      knowledgeCutoff: 'Jun 01, 2024',
      latestUpdate: 'Snapshot 2025-04-16',
      versions: ['o3', 'o3-2025-04-16'],
      limits: { rpm: '500', tpm: '30K', ctx: '200K', out: '100K', batch: '90K', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/o3',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'o4-mini',
      label: 'o4-mini',
      status: 'current',
      summary: 'Smaller reasoning model for faster interactive use.',
      knowledgeCutoff: 'Jun 01, 2024',
      latestUpdate: 'Snapshot 2025-04-16',
      versions: ['o4-mini', 'o4-mini-2025-04-16'],
      limits: { rpm: '1,000', tpm: '100K', ctx: '200K', out: '100K', batch: '1M', tier: 'Tier 1' },
      source: {
        label: 'OpenAI model page',
        url: 'https://developers.openai.com/api/docs/models/o4-mini',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gpt-4o',
      label: 'GPT-4o',
      status: 'legacy',
      summary: 'Older omni general-purpose model still common in deployed apps.',
      knowledgeCutoff: 'See docs',
      latestUpdate: 'Legacy but still active',
      versions: ['gpt-4o'],
      limits: { rpm: 'See docs', tpm: 'See docs', ctx: 'See docs', out: 'See docs', batch: 'See docs', tier: 'Tiered' },
      source: {
        label: 'OpenAI models overview',
        url: 'https://developers.openai.com/api/docs/models',
      },
      trafficProfile: 'balanced-interactive',
    },
  ],
  gemini: [
    {
      id: 'gemini-3.1-pro-preview',
      label: 'Gemini 3.1 Pro Preview',
      status: 'preview',
      summary: 'Current Gemini preview for advanced reasoning, complex problem solving, and agentic coding.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Released Feb 19, 2026',
      versions: ['Preview: gemini-3.1-pro-preview', 'Preview: gemini-3.1-pro-preview-customtools'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: '5M', tier: 'Preview / AI Studio' },
      source: {
        label: 'Gemini model page',
        url: 'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gemini-3-flash-preview',
      label: 'Gemini 3 Flash Preview',
      status: 'preview',
      summary: 'Preview Gemini flash model for faster multimodal and agentic work.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Released Dec 17, 2025',
      versions: ['Preview: gemini-3-flash-preview'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: '3M', tier: 'Preview / AI Studio' },
      source: {
        label: 'Gemini model page',
        url: 'https://ai.google.dev/gemini-api/docs/models/gemini-3-flash-preview',
      },
      trafficProfile: 'preview-balanced',
    },
    {
      id: 'gemini-3.1-flash-lite-preview',
      label: 'Gemini 3.1 Flash-Lite Preview',
      status: 'preview',
      summary: 'Newest Gemini low-cost, high-frequency multimodal option.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Released Mar 3, 2026',
      versions: ['Preview: gemini-3.1-flash-lite-preview'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: '10M', tier: 'Preview / AI Studio' },
      source: {
        label: 'Gemini model page',
        url: 'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-lite-preview',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gemini-2.5-pro',
      label: 'Gemini 2.5 Pro',
      status: 'deprecated',
      summary: 'Stable Gemini reasoning model with an announced shutdown window; Google recommends Gemini 3.1 Pro Preview.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Shutdown Jun 17, 2026',
      versions: ['Stable: gemini-2.5-pro'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: '5M', tier: 'Tier-based / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'frontier-reasoning',
    },
    {
      id: 'gemini-2.5-flash',
      label: 'Gemini 2.5 Flash',
      status: 'deprecated',
      summary: 'Stable Gemini Flash model with an announced shutdown window; Google recommends Gemini 3 Flash Preview.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Shutdown Jun 17, 2026',
      versions: ['Stable: gemini-2.5-flash'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: '3M', tier: 'Tier-based / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gemini-2.5-flash-lite',
      label: 'Gemini 2.5 Flash-Lite',
      status: 'deprecated',
      summary: 'Stable Gemini Flash-Lite model with an announced shutdown window; Google recommends Gemini 3.1 Flash-Lite Preview.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Shutdown Jul 22, 2026',
      versions: ['Stable: gemini-2.5-flash-lite'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '65,536', batch: '10M', tier: 'Tier-based / AI Studio' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'high-throughput',
    },
    {
      id: 'gemini-3-pro-preview',
      label: 'Gemini 3 Pro Preview',
      status: 'deprecated',
      summary: 'Shut down Gemini 3 preview kept to show the official migration path to Gemini 3.1 Pro Preview.',
      knowledgeCutoff: 'January 2025',
      latestUpdate: 'Shut down Mar 9, 2026',
      versions: ['Shut down: gemini-3-pro-preview'],
      limits: { rpm: 'N/A', tpm: 'N/A', ctx: '1,048,576', out: '65,536', batch: '5M', tier: 'Shut down' },
      source: {
        label: 'Gemini deprecations',
        url: 'https://ai.google.dev/gemini-api/docs/deprecations',
      },
      trafficProfile: 'preview-balanced',
    },
    {
      id: 'gemini-2.0-flash',
      label: 'Gemini 2.0 Flash',
      status: 'deprecated',
      summary: 'Deprecated stable Flash generation with a documented replacement path.',
      knowledgeCutoff: 'August 2024',
      latestUpdate: 'Shutdown Jun 1, 2026',
      versions: ['gemini-2.0-flash', 'gemini-2.0-flash-001'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '8,192', batch: '10M', tier: 'Deprecated / AI Studio' },
      source: {
        label: 'Gemini model page',
        url: 'https://ai.google.dev/gemini-api/docs/models/gemini-2.0-flash',
      },
      trafficProfile: 'balanced-interactive',
    },
    {
      id: 'gemini-2.0-flash-lite',
      label: 'Gemini 2.0 Flash-Lite',
      status: 'deprecated',
      summary: 'Deprecated Lite generation retained to show its replacement and historical limits.',
      knowledgeCutoff: 'August 2024',
      latestUpdate: 'Shutdown Jun 1, 2026',
      versions: ['gemini-2.0-flash-lite', 'gemini-2.0-flash-lite-001'],
      limits: { rpm: 'AI Studio', tpm: 'AI Studio', ctx: '1,048,576', out: '8,192', batch: '10M', tier: 'Deprecated / AI Studio' },
      source: {
        label: 'Gemini model page',
        url: 'https://ai.google.dev/gemini-api/docs/models/gemini-2.0-flash-lite',
      },
      trafficProfile: 'high-throughput',
    },
  ],
};

const allModels = Object.values(MODEL_CATALOG).flat();

export const MODEL_DETAILS = Object.fromEntries(
  allModels.map((model) => [model.id, model])
);

export const MODELS = Object.fromEntries(
  Object.entries(MODEL_CATALOG).map(([provider, models]) => [
    provider,
    models.map(({ id }) => id),
  ])
);

export const DEFAULT_MODEL_BY_PROVIDER = Object.fromEntries(
  Object.entries(MODEL_CATALOG).map(([provider, models]) => [provider, models[0]?.id])
);

export const MODEL_LIMITS = Object.fromEntries(
  allModels.map((model) => [
    model.id,
    {
      rpm: model.limits.rpm,
      tpm: model.limits.tpm,
      ctx: model.limits.ctx,
      out: model.limits.out,
      batch: model.limits.batch,
      tier: model.limits.tier,
    },
  ])
);

export function getModelDetails(modelId) {
  return MODEL_DETAILS[modelId];
}

export function getTrafficProfileForModel(modelId) {
  const profileKey = MODEL_DETAILS[modelId]?.trafficProfile || DEFAULT_TRAFFIC_PROFILE;
  return TRAFFIC_PROFILES[profileKey] || TRAFFIC_PROFILES[DEFAULT_TRAFFIC_PROFILE];
}
